# docker-compose.yml
version: '3.8'

services:
  # Main API Service
  api:
    build: .
    container_name: fraud-detection-api
    ports:
      - "8001:8000"
      - "9090:9090"  # Prometheus metrics
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=fraud_detection
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=INFO
      - DEBUG=false
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./saved_models:/app/saved_models
      - ./logs:/app/logs
    networks:
      - fraud-detection-network
    restart: unless-stopped

  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: fraud-detection-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=fraud_detection
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secure_password
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - fraud-detection-network
    restart: unless-stopped

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: fraud-detection-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - fraud-detection-network
    restart: unless-stopped

  # MongoDB Express (Web UI)
  mongo-express:
    image: mongo-express:latest
    container_name: fraud-detection-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secure_password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:secure_password@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - fraud-detection-network
    restart: unless-stopped

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: fraud-detection-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - fraud-detection-network
    restart: unless-stopped

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: fraud-detection-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    networks:
      - fraud-detection-network
    restart: unless-stopped

networks:
  fraud-detection-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  prometheus_data:
  grafana_data: